export const SET_USER_ACTION = "SET_CURRENT_USER";
export const TOGGLE_CART_HIDDEN = "TOGGLE_CART_HIDDEN";
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CARD_CLEAR_ITEM = "CARD_CLEAR_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
